### ISSUE TITLE
Are nus-wide-clear.mat and nus-widetc10.mat the same file?

### ISSUE THREAD

**Issue by limycml** [jiangqy/DLFH-TIP2019#1]
According to the link you provided, the downloaded file is  nus-wide-clear.mat，however, in the code you provided, the required file is nus-widetc10.mat. the code is as follows:
code: datapath = os.path.join(args.datapath, 'nus-widetc10.mat'

Which one is the correct file? Can you provide the download address?

**Comment by jiangqy** [comment]
I haven't run python code on nus-wide yet. If you want to test the performance, please use matlab version. @limycml

**Comment by scpmail** [comment]
Can I get matlab link for downloading NUS-WIDE datase .
@jiangqy
