### ISSUE TITLE
Python version requires a clearer description and guidance

### ISSUE THREAD

**Issue by inksong** [jiangqy/DLFH-TIP2019#2]
Some of the files are even empty...

**Comment by jiangqy** [comment]
The guidance can be found in README.md. Please note that we only use python version to present a simple example on FLICKR25K dataset. Hence we only implement DLFH algorithm. I have deleted kdlfh_algo.py file. All experimental results in the paper are based on matlab version. I have updated the README.md.

**Comment by inksong** [comment]
Thx for the reply. After some debugging, the demo has been running successfully, and the results look really good! Quoted from your paper as 'For DCMH, GSPH, SePH, SCM and MLBE, the source codes are kindly provided by their corresponding authors. For the other baselines, we implement them carefully by ourselves. ' Are you willing to share your implementation of CMFH and CCA-ITQ algorithms?  Our team intends to merge several CMH algorithm integrations and integration the source codes into a comprehensive platform. Any integrated code(Python code would be appreciated) is welcome.

**Comment by inksong** [comment]
By the way, I am very grateful for the data collection you provided, but downloading them is really troublesome. Can you provide an index table of 20,015 data in the FLICKR-25K dataset? There is absolutely no way to match the image to the vector you provide. Since they all have more than 20 textual tags, I can't index the images you chose. 24 unique labels without title is also troublesome, because there is no way to manually label these without your label list.

**Comment by jiangqy** [comment]
We can't provide the source codes for CMFH and CCA-ITQ, pls contact to corresponding authors of these papers.
